### ISSUE TITLE
A new species of Stenasellus Dollfus, 1897 from Iran, with a key to the western Asian species (Crustacea, Isopoda, Stenasellidae)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#358] opened 2023-08-20 22:17 UTC
## A new species of Stenasellus Dollfus, 1897 from Iran, with a key to the western Asian species (Crustacea, Isopoda, Stenasellidae)

Dataset link: https://zookeys.pensoft.net/article/23239/list/6/

Region: IRAN

Taxon: Stenasellus tashanicus

Type: occurrence

Why is this important: No pointed locality on GBIF

Priority: high

Bibliographic reference: https://zookeys.pensoft.net/article/23239/list/6/

Dataholders contact information: javad.malek@zrc-sazu.si

Users contact info: javad.malek@zrc-sazu.si

**Comment by ManonGros** [comment] 2023-08-21 09:12
duplicate of https://github.com/gbif/data-mobilization/issues/357

**Closed by ManonGros** 2023-08-21 09:12 UTC
Labels: Needs validation
