### ISSUE TITLE
U.S. ARMY Medical Directorate - Armed Forces Research Institute of Medical Sciences (USAMD-AFRIMS)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#288] opened 2022-11-16 14:28 UTC
## U.S. ARMY Medical Directorate - Armed Forces Research Institute of Medical Sciences (USAMD-AFRIMS)

Region: Southeast Asia

Taxon: Emerging and Infectious diseases

Type: undefined

Why is this important: AFRIMS conducts research on numerous issues of high priority in the health arena.

Priority: medium

License: Unspecified

Comments: Added by KI to remind us to consider prioritizing approaching AFRIMS as a potential data publisher. Their datasets are not available via a server or portal that I am aware of. The link provided is actually the only link or contact information provided on the website as a way of getting in contact with pretty much anyone at the institute.

Dataholders contact information: https://afrims.health.mil/News-and-Resources/Contact-Us/

Users contact info: kingenloff@gbif.org

**Comment by CecSve** [comment] 2022-12-23 09:10
duplicate of https://github.com/gbif/data-mobilization/issues/293?

**Comment by kingenloff** [comment] 2023-02-14 10:28
yes, this is a duplicate. What's best practices for removing from circulation?

**Comment by CecSve** [comment] 2023-02-14 11:14
Just leave a comment saying it is a 'duplicate of XXX' and close the issue. Then it is automatically registered in the open issue. If the issue was provided by someone else, then make sure all relevant information is copied to the open issue as well. I will close this issue now, and it should probably be removed from the project (otherwise it will be listed as 'Done').

**Closed by CecSve** 2023-02-14 11:14 UTC
Labels: Asia, Pacific, health
