### ISSUE TITLE
PREDICTS

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#24] opened 2017-02-12 09:03 UTC
## PREDICTS

Dataset link: http://data.nhm.ac.uk/dataset/902f084d-ce3f-429f-a6a5-23162c73fdf7

Region: Global

Taxon: All

Type: occurrence

Why is this important: Claimed to be &#39;the largest and most geographically and taxonomically representative database of spatial comparisons of biodiversity that has been collated to date&#39;. Dataset is &#39;collated from published studies a large, reasonably representative database of comparable samples of biodiversity from multiple sites that differ in the nature or intensity of human impacts relating to land use.&quot; 2016 release contains &#39;more than 3.2 million records sampled at over 26,000 locations and representing over 47,000 species&#39;.

Priority: high

Bibliographic reference: http://dx.doi.org/10.1002/ece3.2579

Dataholders contact information: l.hudson@nhm.ac.uk

Users contact info: kcopas@gbif.org

**Comment by kbraak** [comment] 2017-02-12 21:59
Duplicate of https://github.com/gbif/data-mobilization/issues/20

**Closed by kbraak** 2017-02-12 21:59 UTC
Labels: Needs validation
