### ISSUE TITLE
Xeno-Canto

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#109] opened 2018-02-02 12:38 UTC
## Xeno-Canto

Dataset link: https://www.xeno-canto.org/

Region: global

Taxon: Aves

Type: occurrence

Why is this important: 387614 Recordings of 9797 bird species (as of 2 feb 2018)

Priority: medium

License: Unspecified

Comments: Increase of bird occurrences with multimedia - to check if GBIF is not indexing these occurrences already e.g. via eBird

Users contact info: dschigel

**Comment by kcopas** [comment] 2018-02-02 13:24
Lots of runs at them. They seem basically amenable, but it's not a big priority. Certainly best done through Henk and NLBIF. If they're still funded by Naturalis, the change in NLBIF's location could help.

**Comment by kcopas** [comment] 2018-04-12 11:57
Closing—duplicate of #12

**Closed by kcopas** 2018-04-12 11:57 UTC
Labels: Needs validation
