### ISSUE TITLE
OdoBD occurrence

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#179] opened 2020-07-05 14:54 UTC
## OdoBD occurrence

Dataset link: http://odobd.org/download

Region: Bangladesh

Taxon: Odonata

Type: occurrence

Why is this important: The database will be a valuable resource for understanding diversity, distributions, extinction risks and conservation planning of the Odonata of Bangladesh. Moreover, the phenotypic, spatial and temporal data of Odonata of Bangladesh datasets can be integrated with other regional datasets for analyzing macroevolutionary trends and to monitor the effect of climate change on odonates.

Priority: medium

Bibliographic reference: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0231727

**Comment by CecSve** [comment] 2022-05-30 12:35
Duplicate of https://github.com/gbif/data-mobilization/issues/180

**Closed by CecSve** 2022-05-30 12:35 UTC
Labels: Needs validation
