### ISSUE TITLE
Korina

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#26] opened 2017-02-20 14:05 UTC
## Korina

Dataset link: http://www.korina.info/?q=node/4

Region: Sachsen-Anhalt

Taxon: Invasive plants

Priority: high

Dataholders contact information: Katrin Schneiderkatrin.schneider@ufu.de

**Comment by kbraak** [comment] 2017-02-20 14:11
Duplicate of #25

**Closed by kbraak** 2017-02-20 14:11 UTC
Labels: Needs validation
